import type { ScheduleSlot } from '../../types/schedule'

interface ScheduleTimelineProps {
  slots: ScheduleSlot[]
  notes: string
}

export const ScheduleTimeline = ({ slots, notes }: ScheduleTimelineProps) => {
  return (
    <div className="bg-surface-light border border-surface-border rounded-xl p-6 shadow-card">
      <p className="section-title">Medication Timeline</p>
      <p className="subtle-text mt-1">Optimized spacing generated by the scheduling engine.</p>

      <div className="mt-6 space-y-4 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-brand-blue/30 before:to-brand-blue/30">
        {slots.length === 0 ? (
          <div className="rounded-xl border border-surface-border bg-surface-muted p-4 text-sm text-gray-600 text-center relative z-10">
            No schedule slots were generated.
          </div>
        ) : (
          slots.map((slot, idx) => (
            <div key={`${slot.time}-${idx}`} className="relative z-10">
              <div className="flex items-center gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-full border-4 border-surface-light bg-brand-blue/10 flex items-center justify-center text-xs font-bold text-brand-blue shadow-sm">
                  {slot.time}
                </div>
                <div className="flex-1 rounded-xl border border-surface-border bg-surface-light p-4 shadow-sm hover:shadow-md transition-shadow">
                  <div className="flex flex-wrap gap-2">
                    {slot.medications.map((med) => (
                      <span
                        key={`${slot.time}-${med}`}
                        className="rounded-full border border-surface-border bg-surface-muted px-3 py-1.5 text-xs font-bold tracking-wider text-brand-navy"
                      >
                        {med}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      <div className="mt-6 rounded-xl border border-brand-blue/20 bg-brand-blue/5 p-4 text-sm text-brand-navy flex items-start gap-3">
        <svg className="w-5 h-5 text-brand-blue shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <div>
          <span className="font-bold text-brand-blue block mb-1">Clinical Note</span>
          <span className="text-gray-600 leading-relaxed">{notes}</span>
        </div>
      </div>
    </div>
  )
}
